version: '3'

services:
  web:
    build: ./database
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: HomeBuilder
      POSTGRES_USER: Nata
      POSTGRES_PASSWORD: 12345
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: HomeBuilder
      POSTGRES_USER: Nata
      POSTGRES_PASSWORD: 12345
